# Generated by Django 4.2.16 on 2024-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbio',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
