# Generated by Django 4.2.16 on 2024-09-26 12:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbio', '0003_alter_userbio_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pics/nobody.jpg', max_length=255, verbose_name='image'),
        ),
    ]
