# Generated by Django 4.2.16 on 2024-09-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.CharField(default='Custom date string', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
