# Generated by Django 4.2.16 on 2024-09-30 14:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='decimal_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
    ]
